name: neil_aron_s_application1
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  flutter_barcode_scanner: ^2.0.0
  cached_network_image: ^3.2.1
  carousel_slider: ^4.0.0
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.6
  intl: ^0.18.0
  smooth_page_indicator: ^1.0.0+2
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
    - family: Montserrat
      fonts:
        - asset: assets/fonts/MontserratExtraBoldItalic.ttf
          weight: 800
        - asset: assets/fonts/MontserratRegular.ttf
          weight: 400
        - asset: assets/fonts/MontserratRomanBold.ttf
          weight: 700
        - asset: assets/fonts/MontserratSemiBold.ttf
          weight: 600
        - asset: assets/fonts/MontserratExtraBold.ttf
          weight: 800
        - asset: assets/fonts/MontserratRomanRegular.ttf
          weight: 400
        - asset: assets/fonts/MontserratMedium.ttf
          weight: 500
        - asset: assets/fonts/MontserratRomanLight.ttf
          weight: 300
        - asset: assets/fonts/MontserratRomanMedium.ttf
          weight: 500
        - asset: assets/fonts/MontserratRomanExtraBold.ttf
          weight: 800
        - asset: assets/fonts/MontserratRomanExtraLight.ttf
          weight: 200
    - family: Kameron
      fonts:
        - asset: assets/fonts/KameronBold.ttf
          weight: 700
    - family: Noto Sans
      fonts:
        - asset: assets/fonts/NotoSansSemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoSansRegular.ttf
          weight: 400
